/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const [alias]: typeof import('[package-name]')['[from]']
  const [import-names]: typeof import('[package-name]')['[import-names]']
  const axios: typeof import('axios')['default']
  const ref: typeof import('vue')['ref']
  const useMouse: typeof import('@vueuse/core')['useMouse']
  const useMyFetch: typeof import('@vueuse/core')['useFetch']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { RouteLocationRaw } from 'vue-router'
}
